name = "MacroExercises"
uuid = "9312e4ea-bfd0-48b3-bdcd-b9395a1f683f"
authors = ["Johan Hidding <j.hidding@esciencecenter.nl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
